# Generated by Django 4.2.6 on 2023-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smg', models.IntegerField(max_length=60)),
                ('heavygun', models.IntegerField(max_length=150)),
                ('pistol', models.IntegerField(max_length=30)),
            ],
        ),
    ]
